"use client";
import { useState,type FormEvent } from "react";
import { CalendarPlus,LoaderCircle } from "lucide-react";
import { useRouter } from "next/navigation";

export function CreateMatchForm() {
  const router=useRouter(); const [open,setOpen]=useState(false); const [loading,setLoading]=useState(false); const [message,setMessage]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setMessage("");const data=new FormData(event.currentTarget);const startsAt=new Date(String(data.get("startsAt"))).toISOString();const response=await fetch("/api/matches",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:data.get("title"),sport:data.get("sport"),address:data.get("address"),startsAt,capacity:Number(data.get("capacity"))})});if(response.ok){event.currentTarget.reset();setOpen(false);router.refresh()}else{const body=await response.json().catch(()=>({}));setMessage(body.message??"Não foi possível criar a partida.")}setLoading(false)}
  return <div><button onClick={()=>setOpen(!open)} className="inline-flex h-11 items-center gap-2 rounded-xl bg-emerald-600 px-4 text-sm font-semibold text-white shadow-lg shadow-emerald-900/10 hover:bg-emerald-700"><CalendarPlus size={18}/>{open?"Fechar":"Nova partida"}</button>{open&&<form onSubmit={submit} className="mt-5 grid gap-4 rounded-2xl border border-emerald-100 bg-emerald-50/50 p-5 md:grid-cols-2"><input name="title" required maxLength={120} placeholder="Nome da partida" className="h-11 rounded-xl border border-slate-200 bg-white px-4"/><select name="sport" required className="h-11 rounded-xl border border-slate-200 bg-white px-4"><option value="Futebol">Futebol</option><option value="Futsal">Futsal</option><option value="Society">Society</option></select><input name="address" required maxLength={240} placeholder="Endereço" className="h-11 rounded-xl border border-slate-200 bg-white px-4"/><input name="startsAt" type="datetime-local" required className="h-11 rounded-xl border border-slate-200 bg-white px-4"/><input name="capacity" type="number" min="2" max="100" defaultValue="10" required className="h-11 rounded-xl border border-slate-200 bg-white px-4"/>{message&&<p role="alert" className="self-center text-sm text-red-700">{message}</p>}<button disabled={loading} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 font-semibold text-white md:col-span-2">{loading?<LoaderCircle className="animate-spin" size={18}/>:<CalendarPlus size={18}/>}Criar partida</button></form>}</div>;
}
